--WRITING FACT AND DIMENSION TABLE
--USING CTAS QUERY

USE DATABASE DW_COURSE_DB;
USE SCHEMA INSTACART;

CREATE OR REPLACE TABLE DIM_USERS AS (
    SELECT
        USER_ID
    FROM 
        ORDERS
);

CREATE OR REPLACE TABLE DIM_PRODUCTS AS (
    SELECT 
        PRODUCT_ID, 
        PRODUCT_NAME
    FROM 
        PRODUCTS  
);

CREATE OR REPLACE TABLE DIM_DEPARTMENTS AS (
    SELECT 
        DEPARTMENT_ID,
        DEPARTMENT
    FROM 
        DEPARTMENTS
);

CREATE OR REPLACE TABLE DIM_AISLES AS (
    SELECT
        AISLE_ID,
        AISLE
    FROM
        AISLES
);

CREATE OR REPLACE TABLE DIM_ORDER AS (
    SELECT 
        ORDER_ID,
        ORDER_NUMBER,
        ORDER_DOW,
        ORDER_HOUR_OF_DAY,
        DAYS_SINCE_PRIOR_ORDER
    FROM
        ORDERS
);

CREATE OR REPLACE TABLE FACT_ORDER_PRODUCTS AS (
    SELECT 
        OP.ORDER_ID,
        OP.PRODUCT_ID,
        O.USER_ID,
        P.DEPARTMENT_ID,
        P.AISLE_ID,
        OP.ADD_TO_CART_ORDER,
        OP.REORDERED
    FROM
        ORDER_PRODUCTS OP
    JOIN 
        ORDERS O ON OP.ORDER_ID = O.ORDER_ID
    JOIN 
        PRODUCTS P ON OP.PRODUCT_ID = P.PRODUCT_ID
);

CREATE TABLE fact_order_products AS (
  SELECT
    op.order_id,
    op.product_id,
    o.user_id,
    p.department_id,
    p.aisle_id,
    op.add_to_cart_order,
    op.reordered
  FROM
    order_products op
  JOIN
    orders o ON op.order_id = o.order_id
  JOIN
    products p ON op.product_id = p.product_id
);

USE DATABASE DW_COURSE_DB;
USE SCHEMA INSTACART_DIM_FACT;


CREATE TABLE DW_COURSE_DB.INSTACART_DIM_FACT.DIM_AISLES CLONE DW_COURSE_DB.INSTACART.DIM_AISLES;
CREATE TABLE DW_COURSE_DB.INSTACART_DIM_FACT.DIM_DEPARTMENTS CLONE DW_COURSE_DB.INSTACART.DIM_DEPARTMENTS;
CREATE TABLE DW_COURSE_DB.INSTACART_DIM_FACT.DIM_ORDER CLONE DW_COURSE_DB.INSTACART.DIM_ORDER;
CREATE TABLE DW_COURSE_DB.INSTACART_DIM_FACT.DIM_PRODUCTS CLONE DW_COURSE_DB.INSTACART.DIM_PRODUCTS;
CREATE TABLE DW_COURSE_DB.INSTACART_DIM_FACT.DIM_USERS CLONE DW_COURSE_DB.INSTACART.DIM_USERS;
CREATE TABLE DW_COURSE_DB.INSTACART_DIM_FACT.FACT_ORDER_PRODUCTS CLONE DW_COURSE_DB.INSTACART.FACT_ORDER_PRODUCTS;

USE DATABASE DW_COURSE_DB;
USE SCHEMA INSTACART;

DROP TABLE DW_COURSE_DB.INSTACART.DIM_AISLES;
DROP TABLE DW_COURSE_DB.INSTACART.DIM_DEPARTMENTS;
DROP TABLE DW_COURSE_DB.INSTACART.DIM_ORDER;
DROP TABLE DW_COURSE_DB.INSTACART.DIM_PRODUCTS;
DROP TABLE DW_COURSE_DB.INSTACART.DIM_USERS;
DROP TABLE DW_COURSE_DB.INSTACART.ORDER_PRODUCTS;
UNDROP TABLE DW_COURSE_DB.INSTACART.ORDER_PRODUCTS;

DROP TABLE DW_COURSE_DB.INSTACART.FACT_ORDER_PRODUCTS;

SELECT * FROM DW_COURSE_DB.INSTACART_DIM_FACT.FACT_ORDER_PRODUCTS LIMIT 10;







